### ISSUE TITLE
Invalid rule error

### ISSUE THREAD

**Issue by sentience** [chromaui/storybook-addon-pseudo-states#141]
For a Storybook with this rule in its stylesheet:

```css
@layer utilities {
  @media (hover: hover) {
    body .prc\:hover\:cursor-default:hover {
      cursor: default;
    }
  }
}
```

…I am getting this console error from the pseudo-states add-on:

> SyntaxError: Failed to execute 'insertRule' on 'CSSGroupingRule': the rule 'body .prc\:hover\:cursor-default:hover, body .prc\.pseudo-hover\:cursor-default.pseudo-hover, .pseudo-hover-all body .prc\\:cursor-default { cursor: default; }' is invalid and cannot be parsed.

Looks like perhaps there's an issue with the escaped colons (`\:`) in the selector, which are producing a double backslash in the injected CSS?

**Comment by sentience** [comment]
And another:

```css
@layer utilities {
  body {
    .prc\:focus-within\:border-gray-600 {
      &:focus-within {
        border-color: #524e56;
      }
    }
  }
}
```

> SyntaxError: Failed to execute 'insertRule' on 'CSSGroupingRule': the rule 'body .prc\:focus-within\:border-gray-600:focus-within, body .prc\.pseudo-focus-within\:border-gray-600.pseudo-focus-within, .pseudo-focus-within-all body .prc\\:border-gray-600 { border-color: rgb(82, 78, 86); }' is invalid and cannot be parsed.
