### ISSUE TITLE
Media queries mess up stylesheet override

### ISSUE THREAD

**Issue by filipw01** [chromaui/storybook-addon-pseudo-states#57]
Because index is not incremented [here](https://github.com/chromaui/storybook-addon-pseudo-states/blob/main/src/rewriteStyleSheet.js#L67) (it gets transpiled to `if (!("selectorText" in cssRule)) continue;`, media queries just go to the next rule. This leads to a situation where
```css
@media only screen and (max-width: 790px) {
    .test {
    	background-color: green;
	}
}

.test {
    background-color: blue;
}

.test:hover {
    background-color: red;
}

.test2:hover {
	background-color: white;
}
```
is rewritten to
```css
@media only screen and (max-width: 790px) {
    .test {
    	background-color: green;
	}
}

.test:hover, .pseudo-hover.test, .pseudo-hover .test {
    background-color: red;
}

.test2:hover, .pseudo-hover.test2, .pseudo-hover .test2 {
	background-color: white;
}

.test2:hover {
	background-color: white;
}
```

I will open a PR fixing soon
