### ISSUE TITLE
newRules contain errors, host not removed or modified

### ISSUE THREAD

**Issue by reno1979** [chromaui/storybook-addon-pseudo-states#9]
Our vanilla web components have a css like this

```css
:host(:active) #person{
   border: 1px solid red;
}
```

when a pseudo state is set, the new rule contains an empty host(), which results in a insertRule fail.
See: 
```
Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule ':host(:active) #person, :host(.pseudo-active) :host() #person
```
