### ISSUE TITLE
Psuedo state :has in css doesn't work in preview

### ISSUE THREAD

**Issue by ludvikbrodl** [chromaui/storybook-addon-pseudo-states#96]
If you use sass and a style like:

```css
.toggle {
  :has(:focus-visible) {
    background-color: red;
  }
}
```
The style is not applied in the preview and you get an error message. However if I disable storybook-addon-psuedo-states by removing it from `addons` in the storybook config the style is applied correctly and the error message is gone.

![Screenshot from 2023-11-23 16-34-06](https://github.com/chromaui/storybook-addon-pseudo-states/assets/3493658/377cf1e8-5e3c-4c29-8478-7bc637b1adc5)
