### ISSUE TITLE
pseudo-class in media query is not working

### ISSUE THREAD

**Issue by satoren** [chromaui/storybook-addon-pseudo-states#97]
The following css cannot be used
```css
@media (max-width: 3000px) {
  .button:hover {
    text-decoration: underline;
  }
}
```
I am using tamagui and tried to apply hover, but tamagui adds the media query `@media not all and (hover: none)` to hover without fail, so I am looking for a workaround.
